django_project/urls.py
# django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),
    path("", include("pages.urls")),
    path("jobs/", include("jobs.urls")),
]

jobs/urls.py
"""jobs/urls.py"""

from django.urls import path
from jobs.views import (
    DashboardView, JobsTreeListView, JobsTableListView, TaskUpdateView, MarkActionDoneView, EditActionView,
    EditActivityView, AddActivityView
)

urlpatterns = [
    path('list-tree', JobsTreeListView.as_view(), name='list-tree'),
    path('list-table', JobsTableListView.as_view(), name='list-table'),
    path('task/edit/<int:pk>', TaskUpdateView.as_view(), name='edit-task'),
    path('action/mark-done', MarkActionDoneView.as_view(), name='mark-action-done'),
    path('action/edit/<int:pk>', EditActionView.as_view(), name='edit-action'),
    path('activity/edit/<int:pk>', EditActivityView.as_view(), name='edit-activity'),
    path('activity/add/<int:task_id>', AddActivityView.as_view(), name='add-activity'),
    path('', DashboardView.as_view(), name='dashboard')
]


# from django.contrib import admin
# from django.urls import path
# from .views import (
#     ActionListView,
#     JobListView,
# )

# ### Review - this was to get articles migrations working


# urlpatterns = [
#     path("jobs", JobListView.as_view(), name="job_list"),
# ]

articles/models.py
# articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})

templates/article_delete.html
<!-- templates/article_delete.html -->
{% extends "base.html"%}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ article.title }}"?</p>
    <button class="btn btn-danger ml-2" type="subnit">Confirm</button>
</form>
{% endblock content %}

templates/article_detail.html
<!-- templates/article_detail.html -->
{% extends "base.html" %}

{% block content %}
<div class="article-entry">
    <h2>{{ object.title }}</h2>
    <p>by {{object.author }} | {{object.date }}</p>
    <p>{{ object.body }}</p>
</div>

<p><a href="{% url 'article_edit' article.pk %}">Edit</a> |
    <a href="{% url 'article_delete' article.pk %}">Delete</a>
</p>
<p>Back to <a href="{% url 'article_list' %}">All Articles</a>.</p>
{% endblock content %}

templates/article_edit.html
<!-- templates/article_edit.html -->
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/article_list.html
<!-- templates/article_list.html-->
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}


{% block content %}
{% for article in article_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ article.title }}</span> &middot;
        <span class="text-muted"> by {{ article.author}} | {{ article.date }}</span>
    </div>
    <div class='card-body'>
        {{ article.body}}
    </div>
    <div class="card-footer text-center text-muted">
        <a href="{% url 'article_edit' article.pk %}">Edit</a> |
        <a href="{% url 'article_delete' article.pk %}">Delete</a>
    </div>
</div>
<br />
{% endfor %}
{% endblock content %}

templates/article_new.html
<!-- templates/article_new.html -->
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>New article</h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2">Save</button>
</form>

{% endblock content %}

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Newspaper App{% endblock title %}</title>
    <meta name="viewport" content="width=device-width,
    initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block extra_head %}
    {% endblock extra_head %}
</head>

<body>
    <div class="container">
        <header class="p-3 mb-3 border-bottom">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center
                justify-content-lg-start">
                    <a class="navbar-brand" href="{% url 'home' %}">Newspaper</a>
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
                    mb-md-0">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'article_new' %}" class="nav-link px-2 link-dark">+ New article</a></li>
                    </ul>
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item" href="{% url 'password_change'%}">
                                    Change password</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                        </ul>
                    </div>
                    {% else %}
                    </ul>
                    <div class="text-end">
                        <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
                            Log In</a>
                        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </header>

        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </div>
    {% block extra_body %}
    {% endblock extra_body %}
</body>

</html>

templates/home.html
<!-- templates/home.html -->
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if user.is_authenticated %}
    Hi {{ user.username }}! Your comment is: {{ user.comment }}
    <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a> |
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock content %}

templates/job_list.html
<!-- templates/job_list.html -->
{% extends "base_generic.html" %}

{% block title%} Jobs List {% endblock %}

{% block section%} <h1> Jobs heading </h1> {% endblock%}

{% for row in qs %}
<a row: {{ row }} </a>
    {% endfor %}