django_project/urls.py
# django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),
    path("", include("pages.urls")),
    path("jobs/", include("jobs.urls")),
]

jobs/urls.py
"""jobs/urls.py"""

from django.urls import path
from jobs.views import (
    DashboardView, JobsTreeListView, JobsTableListView, TaskUpdateView, MarkActionDoneView, EditActionView,
    EditActivityView, AddActivityView
)

urlpatterns = [
    path('list-tree', JobsTreeListView.as_view(), name='list-tree'),
    path('list-table', JobsTableListView.as_view(), name='list-table'),
    path('task/edit/<int:pk>', TaskUpdateView.as_view(), name='edit-task'),
    path('action/mark-done', MarkActionDoneView.as_view(), name='mark-action-done'),
    path('action/edit/<int:pk>', EditActionView.as_view(), name='edit-action'),
    path('activity/edit/<int:pk>', EditActivityView.as_view(), name='edit-activity'),
    path('activity/add/<int:task_id>', AddActivityView.as_view(), name='add-activity'),
    path('', DashboardView.as_view(), name='dashboard')
]


# from django.contrib import admin
# from django.urls import path
# from .views import (
#     ActionListView,
#     JobListView,
# )

# ### Review - this was to get articles migrations working


# urlpatterns = [
#     path("jobs", JobListView.as_view(), name="job_list"),
# ]

jobs/models.py
# jobs/models.py
from django.conf import settings
from django.db import models


# Create action table - action_description is static - action_comment is for users
class Action(models.Model):
    action_comment = models.CharField(max_length=200, blank=True, help_text="For users")
    action_description = models.CharField(
        max_length=200, blank=True, help_text="Normally from default"
    )
    action_name = models.CharField(
        max_length=25, blank=False, help_text="Normally from default"
    )
    action_order = models.IntegerField(
        blank=False, default=0, help_text="Normally from default"
    )
    date_done = models.DateField(
        blank=True, null=True, help_text="Set by system when user marks as done"
    )
    task = models.ForeignKey("Task", related_name='actions', on_delete=models.CASCADE)

    def __str__(self):
        return self.action_name


# Create activity table - activity_comment is for users
class Activity(models.Model):
    activity_comment = models.CharField(max_length=200, blank=True)  # For users
    activity_date = models.DateField(auto_now_add=True)
    hours = models.DecimalField(max_digits=5, decimal_places=2, blank=False)
    task = models.ForeignKey("Task", related_name='activities', on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
    )  # Do not delete users - make inactive

    def __str__(self) -> str:
        return self.activity_comment

    class Meta:
        verbose_name_plural = "Activities"


# Create the client table
class Client(models.Model):
    client_code = models.CharField(max_length=10, unique=True, blank=False)
    client_name = models.CharField(max_length=35, blank=False)

    def __str__(self):
        return self.client_name


# # Create default_action table - _comment changed to _description
# class Default_action(models.Model):
#     d_action_description = models.CharField(max_length=200, blank=True)
#     d_action_name = models.CharField(max_length=50, blank=False)

#     def __str__(self):
#         return self.d_action_name

# # Create the default_task table - _comment changed to _description
# class Default_task(models.Model):
#     d_task_description = models.CharField(max_length=35, blank=False)
#     d_task_name = models.CharField(max_length=35, blank=False)

#     def __str__(self):
#         return self.d_task_name

# # Create the defaults_map table
# # This defines the order of default actions for a default task
# #ToDo review
# class Defaults_map(models.Model):
#     d_action_id = models.IntegerField(blank=False)
#     d_action_order = models.IntegerField(blank=False)
#     d_task_id = models.IntegerField(blank=False)


# Create the job table
class Job(models.Model):
    client = models.ForeignKey("Client", related_name='jobs', on_delete=models.CASCADE)
    folder_url = models.CharField(max_length=100, blank=True)
    job_name = models.CharField(max_length=100, blank=False)
    period_end = models.DateField(blank=True)

    def __str__(self):
        return self.job_name


# Create the recur_action table
class Recur_action(models.Model):
    r_action_description = models.CharField(max_length=100, blank=True)
    r_action_name = models.CharField(max_length=80, blank=False)
    r_action_order = models.IntegerField(blank=True)
    recur_task = models.ForeignKey("Recur_task", on_delete=models.CASCADE)

    def __str__(self):
        return self.r_action_name

    class Meta:
        verbose_name_plural = "Recurring Actions"


# # Create the recur_job table
class Recur_job(models.Model):
    FREQUENCIES = [
        ("day", "day"),
        ("month", "month"),
        ("week", "week"),
    ]
    JOB_NAMES = [
        ("EOM", "EOM"),
        ("EOQ", "EOQ"),
        ("Pays", "Pays"),
    ]
    build_delay = models.IntegerField(
        default=0, blank=False, help_text="Days before / after next_period_end"
    )
    client = models.ForeignKey("Client", on_delete=models.CASCADE)
    every = models.IntegerField(blank=False, help_text="Paired with period_freq")
    fin_year = models.IntegerField(blank=False, help_text="Is this needed?")
    # fold_client_url = models.CharField(max_length=120, blank=False)
    # fold_year_url = models.CharField(max_length=120, blank=False)
    job_name_start = models.CharField(max_length=4, choices=JOB_NAMES, blank=False)
    next_build_date = models.DateField(blank=False, help_text="Normally calculated")
    next_period_end = models.DateField(blank=False, help_text="Normally calculated")
    period_freq = models.CharField(max_length=5, choices=FREQUENCIES, blank=False)

    def __str__(self):
        return (
            f"{self.job_name_start} {self.next_period_end} - {self.client.client_name}"
        )

    class Meta:
        verbose_name_plural = "Recurring Jobs"


# Create the recur_task table
class Recur_task(models.Model):
    eofy = models.BooleanField(blank=False, default=False)
    eom = models.BooleanField(blank=False, default=False)
    eom_ex_eoq = models.BooleanField(blank=False, default=False)
    eoq = models.BooleanField(blank=False, default=False)
    recur_job = models.ForeignKey("Recur_job", on_delete=models.CASCADE)
    # r_state_id = models.IntegerField(default=1, blank=False)
    r_task_description = models.CharField(max_length=100, blank=True)
    r_task_name = models.CharField(max_length=50, blank=False)
    r_task_order = models.IntegerField(blank=True)

    def __str__(self):
        return f"{self.r_task_name} {self.recur_job.job_name_start} {self.recur_job.client.client_name}"

    class Meta:
        verbose_name_plural = "Recurring Tasks"


# Create the settings table ToDo is this needed?
class Settings(models.Model):
    end_fin_year = models.DateField(blank=False)


# class State(models.Model):
#     filter_default = models.IntegerField(default=0)
#     is_completed = models.IntegerField(default=0)
#     is_default = models.IntegerField(default=0)
#     not_completed = models.IntegerField(default=0)
#     state_description = models.CharField(max_length=80, blank=True)
#     state_name = models.CharField(max_length=30, blank=False)


# Create the task table - _comment changed to _description
# Choices are subclassed to ensure data integrity.
# ...The first part is not used, 2nd is stored in db,
# ...3rd is displayed - set field length to fit this text.
class Task(models.Model):
    ACT = 1
    AWOK = 2
    AWIN = 3
    COMP = 4
    FUP = 5
    INP = 6
    LOD = 7
    TOI = 8

    STATE_CHOICES = {
        'Action needed': ACT,
        'Await OK to lodge...': AWOK,
        'Await information': AWIN,
        'Completed': COMP,
        'Follow up': FUP,
        'In progress': INP,
        'Lodged - ATO to file': LOD,
        'To invoice something': TOI,
    }

    deadline_date = models.DateField(blank=True, null=False, help_text="Set as needed")
    job = models.ForeignKey("Job", related_name='tasks', on_delete=models.CASCADE)
    review_date = models.DateField(blank=True, null=True, help_text="Set as needed")
    state = models.PositiveSmallIntegerField(
        choices=[(value, key) for key, value in STATE_CHOICES.items()], null=True, blank=True
    )
    task_description = models.CharField(max_length=100, blank=True, default=None)
    task_name = models.CharField(max_length=80, blank=False)
    task_order = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return self.task_name

jobs/forms.py
from django import forms
from django.core.exceptions import ValidationError

from jobs.models import Task, Action, Activity


class ActionForm(forms.ModelForm):
    """Form to edit and action."""

    class Meta:
        model = Action
        fields = ['action_comment']


class ActivityForm(forms.ModelForm):
    """Form to create or edit an activity."""

    class Meta:
        model = Activity
        fields = ['activity_comment', 'hours', ]

    def __init__(self, task_id=None, user=None, *args, **kwargs):
        """Get task_id and user from view."""
        super(ActivityForm, self).__init__(*args, **kwargs)
        self.task_id = task_id
        self.user = user

    def save(self, commit=True):
        """Attach task_id and user from view to instance of activity."""
        activity = super(ActivityForm, self).save(commit=False)

        # Set the task and user for the activity
        if self.task_id:
            activity.task_id = self.task_id
        if self.user:
            activity.user = self.user

        if commit:
            activity.save()
        return activity


class TaskEditForm(forms.ModelForm):
    """Form used to edit a task."""

    class Meta:
        model = Task
        fields = ['id', 'deadline_date', 'review_date', 'state', 'task_description']

    def __init__(self, *args, **kwargs):
        """Check if state of a task is completed or not:

        if completed, disable changing state
        if not completed, remove completed from state choices
        """
        super(TaskEditForm, self).__init__(*args, **kwargs)
        instance = kwargs.get('instance')

        if instance:
            if instance.state == Task.COMP:
                self.fields['state'].widget.attrs['disabled'] = True
            else:
                self.fields['state'].choices = [
                    (choice[0], choice[1]) for choice in self.fields['state'].choices if choice[0] != Task.COMP
                ]

    def clean(self):
        """Clean data for form."""
        cleaned_data = super().clean()
        instance = self.instance

        # if there is not state in data, use the old state
        if not cleaned_data['state']:
            cleaned_data['state'] = instance.state
        new_state = cleaned_data.get('state')

        # Check if the state is being changed to "Completed"
        if new_state == Task.COMP and instance.state != Task.COMP:
            raise ValidationError("You cannot change the state to 'Completed'.")

        # Check if the state is being changed from "Completed"
        if new_state != Task.COMP and instance.state == Task.COMP:
            raise ValidationError("You cannot change the state from 'Completed'.")

        return cleaned_data

jobs/templates/jobs/action-update.html
{% extends "base.html"%}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5>{{ task.task_name }}</h5>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

jobs/templates/jobs/activity-update.html
{% extends "base.html"%}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5>{{ task.task_name }}</h5>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

jobs/templates/jobs/dashboard.html
{% extends "base.html"%}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Filter</h5>
                    <form id="task-filters-form" method="post" action="{% url 'list-tree' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="searchInput" class="form-label">Client Name Contains...</label>
                            <div class="input-group">
                                <input type="text" class="form-control filter-input" value="{{ client_name }}" name="client_name" id="client-name">
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="searchInput" class="form-label">Task Name Contains...</label>
                            <div class="input-group">
                                <input type="text" class="form-control filter-input" value="{{ task_name }}" name="task_name" id="task-name">
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="category">Deadline Dates:</label>
                            <div class="row">
                                <div class="col">
                                    <div class="mb-3">
                                        <label for="startDate">Start Date:</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control date-selector" value="{{ start_date_deadline }}" name="start_date_deadline" id="start-date-deadline" placeholder="dd/mm/yyyy">
                                            <button class="btn input-icon-btn" type="button">
                                                <i class="bi bi-calendar"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="mb-3">
                                        <label for="endDate">End Date:</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control date-selector" value="{{ end_date_deadline }}" name="end_date_deadline" id="end-date-deadline" placeholder="dd/mm/yyyy">
                                            <button class="btn input-icon-btn" type="button">
                                                <i class="bi bi-calendar"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="alert alert-danger" id="deadline-date-error"></div>
                            <button class="btn btn-primary" id="clear-dates-deadline">Clear Dates</button>
                        </div>
                        <div class="mb-3">
                            <label for="category">Review Dates:</label>
                            <div class="row">
                                <div class="col">
                                    <div class="mb-3">
                                        <label for="startDate">Start Date:</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control date-selector" value="{{ start_date_review }}" name="start_date_review" id="start-date-review" placeholder="dd/mm/yyyy">
                                            <button class="btn input-icon-btn" type="button">
                                                <i class="bi bi-calendar"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="mb-3">
                                        <label for="endDate">End Date:</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control date-selector" value="{{ end_date_review }}" name="end_date_review" id="end-date-review" placeholder="dd/mm/yyyy">
                                            <button class="btn input-icon-btn" type="button">
                                                <i class="bi bi-calendar"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="alert alert-danger" id="review-date-error"></div>
                            <button class="btn btn-primary" id="clear-dates-review">Clear Dates</button>
                        </div>
                        <div class="mb-3">
                            <label for="task-state">Task State:</label>
                            <select class="form-select" name="task_state" id="task-state">
                                <option value="" selected></option>
                                <option value="not_completed">Not Completed</option>
                                {% for key, value in task_states.items %}
                                    <option value="{{ value }}" {% if value == task_state %}selected{% endif %}>{{ key }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-check hidden">
                            <input class="form-check-input" type="checkbox" id="show-completed-actions">
                            <label class="form-check-label" for="show-completed-actions">
                                Show completed actions
                            </label>
                        </div>
                        <input type="hidden" id="display" name="display">
                        <button class="btn btn-primary" id="show-tree">Tree</button>
                        <button class="btn btn-primary" id="show-table">Table</button>
                        <button class="btn btn-primary">Close</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_body %}
    <script src="{% static 'js/filters.js' %}"></script>
    <script>
        $(document).ready(function() {
            hideErrors();
            const calender = flatpickr(".date-selector", {
                dateFormat: "d/m/Y",
            });
            $('#show-tree').click(event => {
                event.preventDefault();
                if (validateData()){
                    $taskFilterForm.attr('action', "{% url 'list-tree' %}");
                    hideErrors();
                    $taskFilterForm.submit();
                }
            });

            $('#show-table').click(event => {
                event.preventDefault();
                if (validateData()){
                    $taskFilterForm.attr('action', "{% url 'list-table' %}");
                    hideErrors();
                    $taskFilterForm.submit();
                }
            });
            $('.input-icon-btn').click(function(event){
                event.preventDefault();
                handleIconClick(this);
            })
        });
    </script>
{% endblock extra_body %}

jobs/templates/jobs/table-results.html
{% extends "base.html"%}
{% load static %}

{% block content %}
    {% if tasks %}
        <table class="table table-striped table-bordered">
            <thead>
                <tr style="text-align: center">
                    <th>Client</th>
                    <th>Job name</th>
                    <th>Task</th>
                    <th>Task Description</th>
                    <th>Review Date</th>
                    <th>State</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                    <tr class="task-table-row" onclick="window.location='{% url 'edit-task' task.id %}?previous_url={{ request.path }}'">
                        <td>{{ task.job.client.client_name }}</td>
                        <td>Pays {{ task.job.period_end }} - {{ task.job.job_name }}</td>
                        <td>{{ task.task_name }}</td>
                        <td>{{ task.task_description }}</td>
                        <td>{{ task.review_date }}</td>
                        <td>{{ task.get_state_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h5>No results found</h5>
    {% endif %}
    <div class="row">
        <div class="col">
            <script>function goBack(){window.location.href='{% url "dashboard" %}?load=true'}</script>
            <button class="btn btn-primary" onclick="goBack()">Go Back</button>
        </div>
    </div>
{% endblock content %}

{% block extra_body %}
    <script src="{% static 'js/tree.js' %}"></script>
{% endblock extra_body %}

jobs/templates/jobs/task-update.html
{% extends "base.html"%}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5>{{ task.task_name }}</h5>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card" style="margin-bottom: 10px">
                <div class="card-body">
                    {% if task.actions.all %}
                        <p>Actions</p>
                        <div style="text-align: end">
                            <div style="display: inline-block" class="form-check">
                                <input class="form-check-input" type="checkbox" data-id="{{ action.id }}" id="show-completed-actions">
                                <label class="form-check-label" for="show-completed-actions">
                                    Show Completed Actions
                                </label>
                            </div>
                            <button class="btn btn-primary" id="mark-done-btn" disabled>Mark as Done</button>
                        </div>
                        <table class="table table-striped">
                            <thead>
                                <tr style="text-align: center">
                                    <th>
                                         <div class="form-check">
                                             <input class="form-check-input" type="checkbox" id="check-all">
                                         </div>
                                    </th>
                                    <th>Action Name</th>
                                    <th>Action Description</th>
                                    <th>Action Comment</th>
                                    <th>Done</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for action in task.actions.all %}
                                    <tr class="task-table-row" data-isCompleted="{% if action.date_done %}1{% else %}0{% endif %}">
                                        <td>
                                            <div class="form-check">
                                                <input class="form-check-input action-checkbox" type="checkbox" data-id="{{ action.id }}">
                                            </div>
                                        </td>
                                        <td onclick="window.location='{% url 'edit-action' action.id %}'">{{ action.action_name }}</td>
                                        <td onclick="window.location='{% url 'edit-action' action.id %}?previous_url={{ request.get_full_path }}'">{{ action.action_description }}</td>
                                        <td onclick="window.location='{% url 'edit-action' action.id %}?previous_url={{ request.get_full_path }}'">{{ action.action_comment }}</td>
                                        <td onclick="window.location='{% url 'edit-action' action.id %}?previous_url={{ request.get_full_path }}'">{{ action.date_done }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <h5>No actions found</h5>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card" style="margin-bottom: 10px">
                <div class="card-body">
                    <div class="row">
                        <p class="col-6">Activities</p>
                        <div class="col-6" style="text-align: end">
                            <a href="{% url 'add-activity' task.id %}?previous_url={{ request.get_full_path }}" class="btn btn-primary">Add New</a>
                        </div>
                    </div>
                    <table class="table table-striped">
                        <thead>
                            <tr style="text-align: center">
                                <th>Activity Date</th>
                                <th>Hours</th>
                                <th>User</th>
                                <th>Activity Comment</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for activity in task.activities.all %}
                                <tr class="task-table-row">
                                    <td onclick="window.location='{% url 'edit-activity' activity.id %}?previous_url={{ request.get_full_path }}'">{{ activity.activity_date }}</td>
                                    <td onclick="window.location='{% url 'edit-activity' activity.id %}?previous_url={{ request.get_full_path }}'">{{ activity.hours }}</td>
                                    <td onclick="window.location='{% url 'edit-activity' activity.id %}?previous_url={{ request.get_full_path }}'">{{ activity.user.username }}</td>
                                    <td onclick="window.location='{% url 'edit-activity' activity.id %}?previous_url={{ request.get_full_path }}'">{{ activity.activity_comment }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_body %}
    <script src="{% static 'js/editTask.js' %}"></script>
    <script>
        $markDoneBtn.on('click', () => {
            $.ajax({
                type: 'POST',
                url: '{% url "mark-action-done" %}',
                data: JSON.stringify({'ids': selectedIds}),
                contentType: 'application/json',
                headers: {
                    'X-CSRFToken': getCookie('csrftoken'), // Include the CSRF token in the request headers
                },
                success: function(response) {
                    location.reload();
                },
                error: function(error) {
                    // Handle errors here
                    console.error('POST request failed:', error);
                }
            });
        })
    </script>
{% endblock extra_body %}